CREATE SEQUENCE IF NOT EXISTS estoque_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS estoque (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('estoque_id_seq'),
    nome VARCHAR(255) NOT NULL,
    sku VARCHAR(255) UNIQUE NOT NULL,
    quantidade INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_tmsp TIMESTAMP WITHOUT TIME ZONE
);